package com.fleetbilling.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PositiveOrZero;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Represents the financial invoice generated by a BillingRun.
 *
 * <p>One BillingRun produces exactly one Invoice.
 * The Invoice is the document that gets sent to the client for payment.
 *
 * <p>ALL monetary values are stored in PAISA (Long).
 * Why paisa instead of BigDecimal on the DB?
 * - Integer arithmetic is exact and never rounds.
 * - ₹30,000.00 = 3,000,000 paisa stored as BIGINT — no precision loss.
 * - The application layer converts to BigDecimal (or ₹X.XX string) only for display.
 *
 * <p>Relationships:
 * <pre>
 *   BillingRun 1 ---- 1 Invoice   (OneToOne: FK billing_run_id in invoices table)
 *   Vehicle    1 ---- N Invoice   (denormalised for easy querying by vehicle)
 *   Invoice    1 ---- N InvoiceItem
 * </pre>
 *
 * <p>Index on invoiceNumber speeds up invoice lookup by reference number.
 */
@Entity
@Table(
        name = "invoices",
        uniqueConstraints = {
                @UniqueConstraint(name = "uk_invoice_number",      columnNames = "invoice_number"),
                @UniqueConstraint(name = "uk_invoice_billing_run", columnNames = "billing_run_id")
        },
        indexes = {
                @Index(name = "idx_invoice_vehicle", columnList = "vehicle_id")
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Invoice {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The billing run that produced this invoice (One-to-One).
     *
     * <p>The FK (billing_run_id) lives in the invoices table.
     * The unique constraint on billing_run_id enforces the 1:1 relationship at the DB level.
     *
     * <p>FetchType.LAZY — avoid loading the entire BillingRun when querying invoice lists.
     */
    @NotNull
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "billing_run_id", nullable = false,
                foreignKey = @ForeignKey(name = "fk_invoice_billing_run"))
    private BillingRun billingRun;

    /**
     * Denormalised vehicle reference — makes it easy to find all invoices for a vehicle
     * without joining through BillingRun. Matches the vehicle in billingRun.
     */
    @NotNull
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "vehicle_id", nullable = false,
                foreignKey = @ForeignKey(name = "fk_invoice_vehicle"))
    private Vehicle vehicle;

    /**
     * Human-readable invoice reference. Example: "INV-2024-09-0042"
     * Used in payment records, accounting systems, and client communications.
     */
    @NotBlank
    @Column(nullable = false, name = "invoice_number", length = 100)
    private String invoiceNumber;

    /**
     * Date the invoice was issued.
     * LocalDate — invoices are dated by calendar day, not timestamp.
     */
    @NotNull
    @Column(nullable = false, name = "invoice_date")
    private LocalDate invoiceDate;

    /**
     * Sum of all InvoiceItem amounts, in PAISA, before tax.
     * subtotalPaisa + taxPaisa = totalPaisa
     */
    @NotNull
    @PositiveOrZero
    @Column(nullable = false, name = "subtotal_paisa")
    private Long subtotalPaisa;

    /**
     * GST or other applicable tax amount, in PAISA.
     * Tax calculation logic will be added in a later phase.
     */
    @NotNull
    @PositiveOrZero
    @Column(nullable = false, name = "tax_paisa")
    private Long taxPaisa;

    /**
     * Total amount due from the client, in PAISA.
     * = subtotalPaisa + taxPaisa
     */
    @NotNull
    @PositiveOrZero
    @Column(nullable = false, name = "total_paisa")
    private Long totalPaisa;

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(nullable = false)
    private LocalDateTime updatedAt;
}
